### ISSUE TITLE
[NEED ASSIST] Force locale 

### ISSUE THREAD

**Issue by alna26** [Adyen/adyen-flutter#152] opened 2024-04-11 13:17 UTC
Could you please tell how to force locale, I'm using sessions flow and drop-in. After adding shopperLocale in DropInConfiguration, it still picks-up device's setting locale on iOS (somehow adding  cardConfiguration: const CardConfiguration() in DropInConfiguration fixed the issue, but when trying to customize the texts it shows the default translations) . 

final dropInConfiguration = DropInConfiguration(
      environment: configuration.environment,
      clientKey: configuration.clientKey,
      countryCode: configuration.countryCode,
      shopperLocale: configuration.shopperLocale,
      amount: configuration.amount,
      cardConfiguration: const CardConfiguration(),
      applePayConfiguration: ApplePayConfiguration(
        merchantId: applePayMerchantId,
        merchantName: applePayMerchantName,
        allowOnboarding: true,
      ),
    )

**Comment by Robert-SD** [comment] 2024-04-15 07:43
Hello @alna26, 
I would like to help you. Could you quickly describe how you customize the texts?

**Comment by Robert-SD** [comment] 2024-04-22 15:43
Hi @alna26, I just want to follow up on your question. Do you need further assistance?

**Comment by Robert-SD** [comment] 2024-05-02 08:45
Hi @alna26, we would like to close this issue but in case you still need support, please feel free to reopen it.

**Closed by Robert-SD** 2024-05-02 08:45 UTC
Labels: question

**Comment by Robert-SD** [comment] 2024-07-02 15:23
Hi @matmicro, 
I assume you are using the sessions flow? In that case, could you provide a value for shopperLocale e.g. "fr-FR" when using our /sessions endpoint?
In addition, could you set the shopperLocale value inside the DropInConfiguration also to "fr-FR"? That should change the language to French.

**Comment by Robert-SD** [comment] 2024-07-07 11:53
Hello @matmicro, 

sure, I will try to reproduce it so we can solve it together. 
In order to pin down the problem, I would like to clarify the flow you are using. Is it the sessions flow
 ```dart
final PaymentResult paymentResult = await AdyenCheckout.session.startDropIn(
        dropInConfiguration: dropInConfiguration,
        checkout: sessionCheckout,
);
```

or the advanced flow?
```dart
final PaymentResult paymentResult = await AdyenCheckout.advanced.startDropIn(
       dropInConfiguration: dropInConfiguration,
       paymentMethods: paymentMethodsResponse,
       checkout: advancedCheckout,
);
```

In case of the the sessions flow, could you check the shopperLocale value you send when fetching a session via our[/sessions API](https://docs.adyen.com/api-explorer/Checkout/71/post/sessions#request-shopperLocale)? Do you send "fr-FR" there as well? You need to send this value in order to specify the language of the payment method list because it is part of the session itself. The session language cannot be adjusted later. 
It is therefore necessary to provide the shopperLocale in both: the sessions request and the dropInConfiguration. 

This is the result of the example. Is this your expected behavior? 

Payment method list             |  Card payment
:-------------------------:|:-------------------------:
![](https://github.com/Adyen/adyen-flutter/assets/13377878/70d69b7e-a96e-4496-8ef8-a5651d265039)  |  ![](https://github.com/Adyen/adyen-flutter/assets/13377878/b0ae0185-043e-42b7-8ff3-61f79b764394)
